# Generated by Django 3.1.7 on 2021-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210320_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
