# Generated by Django 3.1.7 on 2021-04-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210322_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcart',
            old_name='total',
            new_name='subtotal',
        ),
    ]
