# Generated by Django 3.1.7 on 2021-07-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210722_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='cart.cart'),
        ),
    ]
