# Generated by Django 3.1.7 on 2021-07-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210729_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_status',
            new_name='status',
        ),
    ]
