# Generated by Django 3.1.7 on 2021-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210320_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
