# Generated by Django 3.1.7 on 2021-06-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210625_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
