# Generated by Django 3.1.7 on 2021-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210320_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='qty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
