# Generated by Django 3.1.7 on 2021-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210630_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='product.Category'),
        ),
    ]
