# Generated by Django 3.1.7 on 2021-03-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210320_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='products',
        ),
    ]
