# Generated by Django 3.1.7 on 2021-07-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210630_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
