# Generated by Django 3.1.7 on 2021-03-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210322_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(height_field='height', upload_to='media/', width_field='width'),
        ),
    ]
