# Generated by Django 3.1.7 on 2021-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210504_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_type',
            field=models.TextField(choices=[('O', 'Other'), ('PF', 'Product Front'), ('PB', 'Product Back'), ('M', 'With Model(s)')], default='O', max_length=2),
        ),
    ]
