# Generated by Django 3.1.7 on 2021-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_gallery_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(default='', max_length=255),
        ),
    ]
